sonar.projectKey=gohilhitraj2019-stack_pizza
sonar.organization=gohilhitraj2019-stack
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=static/js/**,static/css/adminlte*.css,static/css/*.map 